DROP TABLE IF EXISTS TBL_EMPLOYEES;
 
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);


DROP TABLE IF EXISTS TBL_CUSTOMERS;
 
CREATE TABLE TBL_CUSTOMERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL,
  city_id INT,
  FOREIGN KEY (city_id)
  REFERENCES TBL_CITIES(id)
);


DROP TABLE IF EXISTS TBL_CITIES;
 
CREATE TABLE TBL_CITIES (
  id INT AUTO_INCREMENT PRIMARY KEY,
  city_name VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS TBL_DISTRICTS;
 
CREATE TABLE TBL_DISTRICTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  district_name VARCHAR(250) NOT NULL,
  city_id INT,
  FOREIGN KEY (city_id)
  REFERENCES TBL_CITIES(id)
);


DROP TABLE IF EXISTS TBL_SENSORS;
 
CREATE TABLE TBL_SENSORS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sensor_name VARCHAR(250) NOT NULL,
  co2_emission_level VARCHAR(250) NOT NULL,
  createdAt TIMESTAMP,
  district_id INT,
  FOREIGN KEY (district_id)
  REFERENCES TBL_DISTRICTS(id)
);



